# Other Popular Machine Learning Methods

### Segment 1 - Association Rule Mining Using Apriori Algorithm

In [22]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [23]:
grocery = pd.read_csv('Ex_Files_Python_Data_Science_EssT_Pt2/Exercise Files/Data/groceries.csv')

In [24]:
grocery.head()

,1,2,3,4,5,6,7,8,9
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN

Transaction data needs to be in sparse format for association rules, so we have to convert in.

## Data Conversion

In [25]:
basket_sets = pd.get_dummies(grocery)

In [26]:
basket_sets.head()

,1_Instant food products,1_UHT-milk,1_artif. sweetener,1_baby cosmetics,1_bags,1_baking powder,1_bathroom cleaner,1_beef,1_berries,1_beverages,...,9_sweet spreads,9_tea,9_vinegar,9_waffles,9_whipped/sour cream,9_white bread,9_white wine,9_whole milk,9_yogurt,9_zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Support Calculation

In [27]:
apriori(basket_sets, min_support=0.02) # get the item indexes that has the frequency of 0.2 or above.

     support    itemsets
0   0.030421         (7)
1   0.034951        (17)
2   0.029126        (23)
3   0.049191        (26)
4   0.064401        (47)
5   0.044660        (83)
6   0.024272        (90)
7   0.040453        (92)
8   0.038835        (99)
9   0.033981       (100)
10  0.076052       (105)
11  0.028803       (111)
12  0.044984       (123)
13  0.073463       (130)
14  0.022977       (131)
15  0.028803       (159)
16  0.058900       (217)
17  0.022977       (224)
18  0.040129       (232)
19  0.036893       (233)
20  0.031068       (243)
21  0.034628       (256)
22  0.062136       (263)
23  0.028479       (264)
24  0.045955       (351)
25  0.033010       (366)
26  0.024272       (378)
27  0.057929       (397)
28  0.023301       (398)
29  0.020712       (479)
30  0.024595       (497)
31  0.024272       (510)
32  0.033333       (531)
33  0.023301       (532)
34  0.020065       (631)
35  0.021036  (217, 397)

In [28]:
apriori(basket_sets, min_support=0.02, use_colnames=True)

     support                            itemsets
0   0.030421                            (1_beef)
1   0.034951                     (1_canned beer)
2   0.029126                         (1_chicken)
3   0.049191                    (1_citrus fruit)
4   0.064401                     (1_frankfurter)
5   0.044660                (1_other vegetables)
6   0.024272                       (1_pip fruit)
7   0.040453                            (1_pork)
8   0.038835                      (1_rolls/buns)
9   0.033981                 (1_root vegetables)
10  0.076052                         (1_sausage)
11  0.028803                            (1_soda)
12  0.044984                  (1_tropical fruit)
13  0.073463                      (1_whole milk)
14  0.022977                          (1_yogurt)
15  0.028803                    (2_citrus fruit)
16  0.058900                (2_other vegetables)
17  0.022977                       (2_pip fruit)
18  0.040129                      (2_rolls/buns)
19  0.036893                 (2_root vegetables)
20  0.031068                            (2_soda)
21  0.034628                  (2_tropical fruit)
22  0.062136                      (2_whole milk)
23  0.028479                          (2_yogurt)
24  0.045955                (3_other vegetables)
25  0.033010                      (3_rolls/buns)
26  0.024272                            (3_soda)
27  0.057929                      (3_whole milk)
28  0.023301                          (3_yogurt)
29  0.020712                (4_other vegetables)
30  0.024595                      (4_rolls/buns)
31  0.024272                            (4_soda)
32  0.033333                      (4_whole milk)
33  0.023301                          (4_yogurt)
34  0.020065                      (5_rolls/buns)
35  0.021036  (3_whole milk, 2_other vegetables)

The list is full of items but not combinations of items, so we lower the min_support to get more return data. And add in another column to see the number of items in each combinations.

In [33]:
df = basket_sets

frequent_itemsets = apriori(df, min_support=0.002, use_colnames=True)

frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

      support                                           itemsets  length
0    0.006472                                       (1_UHT-milk)       1
1    0.030421                                           (1_beef)       1
2    0.011974                                        (1_berries)       1
3    0.008414                                      (1_beverages)       1
4    0.014887                                   (1_bottled beer)       1
..        ...                                                ...     ...
844  0.002265    (5_other vegetables, 3_pip fruit, 6_whole milk)       3
845  0.002589  (3_root vegetables, 5_whole milk, 4_other vege...       3
846  0.002913                   (4_curd, 5_yogurt, 3_whole milk)       3
847  0.003236  (5_other vegetables, 6_whole milk, 4_root vege...       3
848  0.002265       (5_other vegetables, 7_butter, 6_whole milk)       3

[849 rows x 3 columns]

However, we are still seeing those one-item purchases. We try to filter them out here.

In [35]:
frequent_itemsets[frequent_itemsets['length'] >= 3]

      support                                           itemsets  length
820  0.002589    (2_root vegetables, 3_other vegetables, 1_beef)       3
821  0.002589      (1_chicken, 3_whole milk, 2_other vegetables)       3
822  0.002589  (1_citrus fruit, 3_whole milk, 2_other vegetab...       3
823  0.003236    (3_pip fruit, 1_citrus fruit, 2_tropical fruit)       3
824  0.002589  (3_other vegetables, 1_citrus fruit, 4_whole m...       3
825  0.002265  (5_other vegetables, 1_frankfurter, 6_whole milk)       3
826  0.002265         (3_other vegetables, 1_pork, 4_whole milk)       3
827  0.003560  (1_root vegetables, 3_whole milk, 2_other vege...       3
828  0.002589                  (3_soda, 1_sausage, 2_rolls/buns)       3
829  0.002265      (3_other vegetables, 4_whole milk, 1_sausage)       3
830  0.002265      (5_whole milk, 4_other vegetables, 1_sausage)       3
831  0.002913  (3_whole milk, 1_tropical fruit, 2_other veget...       3
832  0.002265  (2_citrus fruit, 5_whole milk, 4_other vegetab...       3
833  0.002265       (3_whole milk, 4_butter, 2_other vegetables)       3
834  0.003560         (4_curd, 3_whole milk, 2_other vegetables)       3
835  0.003883       (4_yogurt, 3_whole milk, 2_other vegetables)       3
836  0.002265   (3_whole milk, 6_rolls/buns, 2_other vegetables)       3
837  0.003236    (2_pip fruit, 3_other vegetables, 4_whole milk)       3
838  0.005825  (3_other vegetables, 2_root vegetables, 4_whol...       3
839  0.002265  (3_pip fruit, 4_other vegetables, 2_tropical f...       3
840  0.003560       (5_butter, 3_other vegetables, 4_whole milk)       3
841  0.002913       (3_other vegetables, 5_yogurt, 4_whole milk)       3
842  0.003560       (6_yogurt, 3_other vegetables, 4_whole milk)       3
843  0.002265  (5_other vegetables, 3_pip fruit, 4_root veget...       3
844  0.002265    (5_other vegetables, 3_pip fruit, 6_whole milk)       3
845  0.002589  (3_root vegetables, 5_whole milk, 4_other vege...       3
846  0.002913                   (4_curd, 5_yogurt, 3_whole milk)       3
847  0.003236  (5_other vegetables, 6_whole milk, 4_root vege...       3
848  0.002265       (5_other vegetables, 7_butter, 6_whole milk)       3

## Association Rules

#### Confidence

The percentage of the item C to be purchased if the item A is purchased.

In [36]:
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.5)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(2_sausage),(1_frankfurter),0.011327,0.064401,0.011327,1.000000,15.527638,0.010597,inf
1,(7_pastry),(1_frankfurter),0.005178,0.064401,0.002589,0.500000,7.763819,0.002256,1.871197
2,(2_ham),(1_sausage),0.007120,0.076052,0.004531,0.636364,8.367505,0.003989,2.540858
3,(2_meat),(1_sausage),0.006796,0.076052,0.004854,0.714286,9.392097,0.004338,3.233819
4,(3_beef),(1_sausage),0.004854,0.076052,0.002589,0.533333,7.012766,0.002220,1.979889

#### Lift

How often does item A and item C occurs in the same transaction.

In [37]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(2_citrus fruit),(1_beef),0.028803,0.030421,0.005502,0.191011,6.278986,0.004625,1.198508
1,(1_beef),(2_citrus fruit),0.030421,0.028803,0.005502,0.180851,6.278986,0.004625,1.185618
2,(1_beef),(2_other vegetables),0.030421,0.058900,0.003236,0.106383,1.806173,0.001444,1.053136
3,(2_other vegetables),(1_beef),0.058900,0.030421,0.003236,0.054945,1.806173,0.001444,1.025950
4,(2_root vegetables),(1_beef),0.036893,0.030421,0.005502,0.149123,4.902016,0.004379,1.139506

#### Lift and Confidence (Optimal)

In [39]:
rules[(rules['lift'] >= 5) & (rules['confidence'] >= 0.5)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
93,(2_sausage),(1_frankfurter),0.011327,0.064401,0.011327,1.000000,15.527638,0.010597,inf
137,(7_pastry),(1_frankfurter),0.005178,0.064401,0.002589,0.500000,7.763819,0.002256,1.871197
238,(2_ham),(1_sausage),0.007120,0.076052,0.004531,0.636364,8.367505,0.003989,2.540858
243,(2_meat),(1_sausage),0.006796,0.076052,0.004854,0.714286,9.392097,0.004338,3.233819
258,(3_beef),(1_sausage),0.004854,0.076052,0.002589,0.533333,7.012766,0.002220,1.979889
...,...,...,...,...,...,...,...,...,...
959,"(5_other vegetables, 4_root vegetables)",(6_whole milk),0.005178,0.009385,0.003236,0.625000,66.594828,0.003188,2.641640
960,"(6_whole milk, 4_root vegetables)",(5_other vegetables),0.003883,0.012621,0.003236,0.833333,66.025641,0.003187,5.924272
964,"(5_other vegetables, 7_butter)",(6_whole milk),0.002589,0.009385,0.002265,0.875000,93.232759,0.002241,7.924919
966,"(7_butter, 6_whole milk)",(5_other vegetables),0.002913,0.012621,0.002265,0.777778,61.623932,0.002229,4.443204
968,(7_butter),"(5_other vegetables, 6_whole milk)",0.004207,0.007443,0.002265,0.538462,72.341137,0.002234,2.150539

### Segment 2 - Neural Network with a perceptron

In [75]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [76]:
from sklearn.linear_model import Perceptron

In [77]:
bc = datasets.load_breast_cancer()
bc

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.  For instance, field 0 is Mean Radius, field\n        10 is Radius SE, field 20 is Worst Radius.\n\n        - class:\n                - WDBC-Malignant\n                - WDBC-Benign\n\n    :Summary Statistics:\n\n    ===================================== ====== ======\n                                           Min    Max\n    ===================================== ====== ======\n    radius (mean):                        6.981  28.11\n    texture (mean):                       9.71   39.28\n    perimeter (mean):                     43.79  188.5\n    area (mean):                          143.5  2501.0\n    smoothness (mean):                    0.053  0.163\n    compactness (mean):                   0.019  0.345\n    concavity (mean):                     0.0    0.427\n    concave points (mean):                0.0    0.201\n    symmetry (mean):                      0.106  0.304\n    fractal dimension (mean):             0.05   0.097\n    radius (standard error):              0.112  2.873\n    texture (standard error):             0.36   4.885\n    perimeter (standard error):           0.757  21.98\n    area (standard error):                6.802  542.2\n    smoothness (standard error):          0.002  0.031\n    compactness (standard error):         0.002  0.135\n    concavity (standard error):           0.0    0.396\n    concave points (standard error):      0.0    0.053\n    symmetry (standard error):            0.008  0.079\n    fractal dimension (standard error):   0.001  0.03\n    radius (worst):                       7.93   36.04\n    texture (worst):                      12.02  49.54\n    perimeter (worst):                    50.41  251.2\n    area (worst):                         185.2  4254.0\n    smoothness (worst):                   0.071  0.223\n    compactness (worst):                  0.027  1.058\n    concavity (worst):                    0.0    1.252\n    concave points (worst):               0.0    0.291\n    symmetry (worst):                     0.156  0.664\n    fractal dimension (worst):            0.055  0.208\n    ===================================== ====== ======\n\n    :Missing Attribute Values: None\n\n    :Class Distribution: 212 - Malignant, 357 - Benign\n\n    :Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n    :Donor: Nick Street\n\n    :Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. topic:: References\n\n   - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction \n     for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on \n     Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n     San Jose, CA, 1993.\n   - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and \n     prognosis via linear programming. Operations Research, 43(4), pages 570-577, \n     July-August 1995.\n   - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n     to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994) \n     163-171.',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [78]:
X = bc.data
y = bc.target

X[0:10,]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e+01, 2.553e+01, 1.525e+02, 1.709e+03,
        1.444e-01, 4.245e-01, 4.504e-01, 2.430e-01, 3.613e-01, 8.758e-02],
       [1.142e+01, 2.038e+01, 7.758e+01, 3.861e+02, 1.425e-01, 2.839e-01,
        2.414e-01, 1.052e-01, 2.597e-01, 9.744e-02, 4.956e-01, 1.156e+00,
        3.445e+00, 2.723e+01, 9.110e-03, 7.458e-02, 5.661e-02, 1.867e-02,
        5.963e-02, 9.208e-03, 1.491e+01, 2.650e+01, 9.887e+01, 5.677e+02,
        2.098e-01, 8.663e-01, 6.869e-01, 2.575e-01, 6.638e-01, 1.730e-01],
       [2.029e+01, 1.434e+01, 1.351e+02, 1.297e+03, 1.003e-01, 1.328e-01,
        1.980e-01, 1.043e-01, 1.809e-01, 5.883e-02, 7.572e-01, 7.813e-01,
        5.438e+00, 9.444e+01, 1.149e-02, 2.461e-02, 5.688e-02, 1.885e-02,
        1.756e-02, 5.115e-03, 2.254e+01, 1.667e+01, 1.522e+02, 1.575e+03,
        1.374e-01, 2.050e-01, 4.000e-01, 1.625e-01, 2.364e-01, 7.678e-02],
       [1.245e+01, 1.570e+01, 8.257e+01, 4.771e+02, 1.278e-01, 1.700e-01,
        1.578e-01, 8.089e-02, 2.087e-01, 7.613e-02, 3.345e-01, 8.902e-01,
        2.217e+00, 2.719e+01, 7.510e-03, 3.345e-02, 3.672e-02, 1.137e-02,
        2.165e-02, 5.082e-03, 1.547e+01, 2.375e+01, 1.034e+02, 7.416e+02,
        1.791e-01, 5.249e-01, 5.355e-01, 1.741e-01, 3.985e-01, 1.244e-01],
       [1.825e+01, 1.998e+01, 1.196e+02, 1.040e+03, 9.463e-02, 1.090e-01,
        1.127e-01, 7.400e-02, 1.794e-01, 5.742e-02, 4.467e-01, 7.732e-01,
        3.180e+00, 5.391e+01, 4.314e-03, 1.382e-02, 2.254e-02, 1.039e-02,
        1.369e-02, 2.179e-03, 2.288e+01, 2.766e+01, 1.532e+02, 1.606e+03,
        1.442e-01, 2.576e-01, 3.784e-01, 1.932e-01, 3.063e-01, 8.368e-02],
       [1.371e+01, 2.083e+01, 9.020e+01, 5.779e+02, 1.189e-01, 1.645e-01,
        9.366e-02, 5.985e-02, 2.196e-01, 7.451e-02, 5.835e-01, 1.377e+00,
        3.856e+00, 5.096e+01, 8.805e-03, 3.029e-02, 2.488e-02, 1.448e-02,
        1.486e-02, 5.412e-03, 1.706e+01, 2.814e+01, 1.106e+02, 8.970e+02,
        1.654e-01, 3.682e-01, 2.678e-01, 1.556e-01, 3.196e-01, 1.151e-01],
       [1.300e+01, 2.182e+01, 8.750e+01, 5.198e+02, 1.273e-01, 1.932e-01,
        1.859e-01, 9.353e-02, 2.350e-01, 7.389e-02, 3.063e-01, 1.002e+00,
        2.406e+00, 2.432e+01, 5.731e-03, 3.502e-02, 3.553e-02, 1.226e-02,
        2.143e-02, 3.749e-03, 1.549e+01, 3.073e+01, 1.062e+02, 7.393e+02,
        1.703e-01, 5.401e-01, 5.390e-01, 2.060e-01, 4.378e-01, 1.072e-01],
       [1.246e+01, 2.404e+01, 8.397e+01, 4.759e+02, 1.186e-01, 2.396e-01,
        2.273e-01, 8.543e-02, 2.030e-01, 8.243e-02, 2.976e-01, 1.599e+00,
        2.039e+00, 2.394e+01, 7.149e-03, 7.217e-02, 7.743e-02, 1.432e-02,
        1.789e-02, 1.008e-02, 1.509e+01, 4.068e+01, 9.765e+01, 7.114e+02,
        1.853e-01, 1.058e+00, 1.105e+00, 2.210e-01, 4.366e-01, 2.075e-01]])

In [79]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2, test_size=0.2)

In [80]:
#Normalize the data
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)
standardized_X_train = standardize.fit_transform(X_train)

In [81]:
standardized_X_test[0:10]

array([[-8.70033890e-02, -1.47192915e+00, -1.05373911e-01,
        -2.14796744e-01,  2.05627941e+00, -1.87598213e-01,
         4.34596852e-02,  3.43147297e-01,  4.86932208e-01,
         2.09714918e-01,  4.14837253e-01,  2.38110688e+00,
         5.38167210e-01,  1.89599284e-02,  9.51284468e-01,
         3.16783689e-01,  2.81890431e-01,  2.21465008e+00,
        -3.92766050e-01,  4.44859158e-01, -3.86348896e-01,
        -1.69650664e+00, -4.21900040e-01, -4.45574812e-01,
         2.30418212e-01, -7.55219020e-01, -6.01923711e-01,
        -2.66291739e-01, -1.09776353e+00, -6.55974588e-01],
       [ 1.99890922e-01,  3.57734227e-02,  1.70617903e-01,
         5.53159069e-02, -5.87425771e-01, -1.75255240e-01,
        -4.29667545e-01, -1.13156079e-01,  1.63461323e-01,
        -5.72971116e-01, -5.57505328e-01, -4.83058988e-01,
        -4.70073209e-01, -4.73389614e-01, -6.67093209e-01,
        -2.78187639e-01, -4.79507175e-01, -8.56640651e-02,
        -6.03244595e-01, -3.45331271e-01, -6.99717544e-02,
         1.65328229e-01, -1.54121640e-02, -1.93458640e-01,
        -1.56517441e-01,  2.72403512e-01, -4.86802060e-01,
         4.48440538e-01,  6.06658791e-02,  2.10815740e-02],
       [-1.28858427e+00, -2.18476589e-01, -1.30667757e+00,
        -1.10811237e+00, -1.10358495e+00, -9.73010586e-01,
        -9.37028260e-01, -1.19093144e+00, -5.00154205e-01,
         1.51498602e-01, -3.54683095e-01,  1.34935307e-01,
        -4.15460186e-01, -5.69778125e-01,  1.27441000e+00,
        -7.29146473e-01, -5.98659884e-01, -1.18141995e+00,
         6.73803982e-01, -2.97564507e-01, -1.05986343e+00,
        -1.05077020e-01, -1.07456679e+00, -8.85529613e-01,
         2.01756312e-01, -8.22452427e-01, -1.03332448e+00,
        -1.41981535e+00,  1.97886320e-01, -3.10503765e-01],
       [ 2.25596681e+00,  1.80695930e-01,  2.46110354e+00,
         2.43932842e+00,  2.64747495e+00,  3.06604560e+00,
         3.74431547e+00,  3.29412932e+00,  2.42108802e+00,
         9.62645946e-01,  2.93186493e+00,  5.30519568e-01,
         3.66738838e+00,  3.12271955e+00, -2.60436286e-01,
         3.16602359e+00,  1.61191780e+00,  1.69963377e+00,
         1.13074963e+00,  3.01850128e-01,  2.28829958e+00,
         4.78791638e-01,  2.70844692e+00,  2.30386078e+00,
         1.69695211e+00,  2.71932943e+00,  3.18017493e+00,
         2.59112950e+00,  1.63942316e+00,  7.52568830e-01],
       [ 4.80056983e-02, -6.15106608e-01,  5.23356972e-02,
        -7.84348256e-02, -1.21470339e-02,  1.09177667e-01,
        -1.94582453e-01, -2.64579694e-01,  2.73508119e-01,
         1.51498602e-01, -3.26461077e-01, -7.84246318e-01,
        -2.04359849e-01, -2.93249646e-01, -9.26624888e-01,
         2.14818638e-01,  6.41123119e-02, -8.34258117e-03,
        -2.20457190e-01, -1.82807769e-01,  1.15487362e-02,
        -6.40720538e-01,  4.87114379e-02, -1.09205121e-01,
        -2.47280125e-01,  4.82739217e-01,  4.29942187e-01,
         3.35349988e-01,  1.92108617e-01,  1.83264018e-01],
       [ 1.49091532e+00,  2.49437104e+00,  1.67255550e+00,
         1.56313056e+00, -3.84297047e-01,  1.78636979e+00,
         9.23749291e-01,  1.56901801e+00,  2.10147842e-01,
        -8.13666647e-02,  1.53054768e+00, -5.69145701e-02,
         2.14872625e+00,  1.54680456e+00, -3.15092627e-01,
         1.11463393e+00,  6.95390690e-02,  3.72741876e-01,
        -1.51751759e-01,  3.64471190e-01,  1.63807662e+00,
         1.90143327e+00,  1.92223581e+00,  1.60470156e+00,
        -3.09380909e-01,  1.69047326e+00,  6.63004794e-01,
         1.12999959e+00, -1.47331421e-01,  8.97533275e-01],
       [-7.02982350e-01,  3.10363436e-01, -6.88981602e-01,
        -7.20786500e-01,  8.51150043e-01,  1.12807953e-01,
        -3.26967091e-01, -3.87801931e-01,  5.43622982e-01,
         2.04540134e-01,  2.48139202e-01,  7.81791974e-01,
         4.51521549e-01, -1.39622712e-01,  7.42627873e-01,
        -1.25765656e-01,  1.41266640e-01, -1.33989993e-01,
         1.44155992e+00,  3.08840386e-01, -6.38674224e-01,
         1.68772882e-01, -5.78305869e-01, -6.21814487e-01,
         5.84468106e-02, -4.29537929e-01, -4.15379648e-01,
        -6.04206303e-01,  3.58217572e-01, -2.48296800e-01],
       [-2.95142399e-01, -7.98166616e-01, -3.61652025e-01,
        -3.79881704e-01, -9.51996353e-01, -1.00513862e+00,
        -1.08862232e+00, -1.25465131e+00, -6.60222272e-01,
        -5.18635887e-01, -9.24015264e-01, -1.11888004e+00,
        -9.77869295e-01, -7.05564511e-01, -1.25146918e+00,
        -9.76648239e-01, -8.15305462e-01, -1.39515863e+00,
        -7.97364703e-01, -4.12321244e-01, -4.27109142e-01,
        -8.23287139e-01, -4.92157204e-01, -4.71994653e-01,
        -1.04025937e+00, -7.66321784e-01, -1.28184628e+00,
        -1.41981535e+00, -3.88550511e-01, -2.72399076e-02],
       [-5.62347884e-01, -2.59156591e-01, -5.99859245e-01,
        -6.03283145e-01, -8.43610504e-01, -7.45936198e-01,
        -6.63387848e-01, -7.45273451e-01,  4.66923700e-01,
        -8.65414483e-02, -8.12256074e-01, -4.24824911e-01,
        -8.30834234e-01, -6.80538188e-01, -6.03155603e-01,
        -5.68840594e-01, -3.71443926e-01, -6.30504379e-01,
        -3.01158808e-01, -4.41738581e-01, -5.86268195e-01,
        -1.73743455e-03, -6.42708269e-01, -5.89111878e-01,
        -6.15107845e-01, -4.93687235e-01, -4.21488144e-01,
        -5.58668508e-01,  2.78774159e-01, -1.67760998e-01],
       [ 1.57700582e-01, -1.08292663e+00,  7.32815045e-02,
         3.61672120e-02, -9.81556130e-01, -1.04779448e+00,
        -7.16728393e-01, -6.91919493e-01, -5.70183985e-01,
        -1.22499386e+00, -8.19029358e-01, -1.03450005e+00,
        -7.29485067e-01, -5.76220545e-01, -1.94092426e-01,
        -7.60682056e-01, -4.92248257e-01, -2.66541108e-01,
        -5.39991975e-01, -6.47077413e-01, -1.94193454e-01,
        -1.31759482e+00, -2.21722883e-01, -2.73362551e-01,
        -9.87712548e-01, -9.72956567e-01, -8.17130715e-01,
        -5.97270083e-01, -8.46433455e-01, -1.27304546e+00]])

In [82]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

In [83]:
perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [84]:
y_pred = perceptron.predict(standardized_X_test)

In [85]:
print(y_test)

[1 1 1 0 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1
 0 1 1 0 0 1 1 0 1 1 1 0 0 1 0 1 1 1 0 1 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 0
 1 0 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 1 1 1 0 0 0 1 1 1 1 1 1 0
 0 0 0]

In [86]:
print(y_pred)

[1 1 1 0 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1
 1 1 1 0 0 1 1 0 1 1 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 0 1 0 0 0 1 1 0 1 0
 1 0 1 1 1 0 0 0 0 1 1 0 1 1 1 0 1 1 1 0 0 1 0 0 1 1 1 0 0 0 1 1 1 1 1 1 0
 0 0 0]

In [89]:
print(classification_report(y_test, y_pred))
# we can get the prediction of the value of 0 is 0.93 and 0.94 for the value of 1.

              precision    recall  f1-score   support

           0       0.93      0.91      0.92        45
           1       0.94      0.96      0.95        69

    accuracy                           0.94       114
   macro avg       0.94      0.93      0.94       114
weighted avg       0.94      0.94      0.94       114

### Segment 3 - KNN

In [90]:
import numpy as np
import pandas as pd
import sklearn
import scipy
import urllib

import matplotlib.pyplot as plt
from pylab import rcParams

from sklearn.model_selection import train_test_split
from sklearn import neighbors, preprocessing, metrics

In [91]:
from sklearn.neighbors import KNeighborsClassifier

In [92]:
np.set_printoptions(precision=4, suppress=True)
%matplotlib inline
rcParams['figure.figsize'] = 7, 4
plt.style.use('seaborn-whitegrid')

In [93]:
car = pd.read_csv('Ex_Files_Python_Data_Science_EssT_Pt2/Exercise Files/Data/mtcars.csv')

In [95]:
car.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am','gear',' carb']

X_prime = car[['mpg', 'disp', 'hp', 'wt']].values
y = car.iloc[:, 9].values

In [96]:
X = preprocessing.scale(X_prime)

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=17)

In [99]:
clf = KNeighborsClassifier()
clf.fit(X_train, y_train)
print(clf)

KNeighborsClassifier()

In [100]:
y_pred = clf.predict(X_test)
y_expect = y_test

print(classification_report(y_expect, y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89         4
           1       1.00      0.67      0.80         3

    accuracy                           0.86         7
   macro avg       0.90      0.83      0.84         7
weighted avg       0.89      0.86      0.85         7

Recall: a measure of the model's completeness
1. Of all the points that were labeled 1, only 67% of the results that were returned were truly relevant.
2. Of the entire dataset, 83% of the results that were returned were truly relevant.

High precision + low recall = few results returned, but many of the label predictions that are returned are correct.

### Segment 5 - Naive Bayes Classifiers

1. Multinomial: it's good when features are continuous or categorical and discribe discete frequency count. 

2. Bernoulli: it's good making predictions from binary features.

3. Gaussian: good for making predictions from normally distributed features.

Assumtions: predictors are independent of each other. It also holds a priori assumption just as **all regression models** : the past conditions still hold true; when we make predictions from historical values we will get incorrect results if present circumstances have changed.

In [101]:
import numpy as np
import pandas as pd
import urllib
import sklearn

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [102]:
from sklearn.naive_bayes import BernoulliNB, GaussianNB, MultinomialNB

In [105]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data'

import urllib.request

raw_data = urllib.request.urlopen(url)
dataset = np.loadtxt(raw_data, delimiter=',')
print(dataset[0])

[  0.      0.64    0.64    0.      0.32    0.      0.      0.      0.
   0.      0.      0.64    0.      0.      0.      0.32    0.      1.29
   1.93    0.      0.96    0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.      0.      0.
   0.      0.      0.      0.      0.      0.      0.778   0.      0.
   3.756  61.    278.      1.   ]

In [106]:
X = dataset[:, 0:48]
y = dataset[:, -1]

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=17)

In [109]:
BernNB = BernoulliNB(binarize=True)
BernNB.fit(X_train, y_train)
print(BernNB)

y_expect = y_test
y_pred = BernNB.predict(X_test)

print(accuracy_score(y_expect, y_pred))

BernoulliNB(binarize=True)
0.8577633007600435

In [111]:
MultiNB = MultinomialNB()
MultiNB.fit(X_train, y_train)
print(MultiNB)

y_pred = MultiNB.predict(X_test)

print(accuracy_score(y_expect, y_pred))

MultinomialNB()
0.8816503800217155

In [112]:
GauNB = GaussianNB()
GauNB.fit(X_train, y_train)
print(GauNB)

y_pred = GauNB.predict(X_test)

print(accuracy_score(y_expect, y_pred))

GaussianNB()
0.8197611292073833

Try to improve model performance by tuning the parameters (trail and error)

In [113]:
BernNB = BernoulliNB(binarize=0.1)
BernNB.fit(X_train, y_train)
print(BernNB)

y_expect = y_test
y_pred = BernNB.predict(X_test)

print(accuracy_score(y_expect, y_pred))

BernoulliNB(binarize=0.1)
0.9109663409337676

### Segment 6 - Ensemble methods with random forest

In [114]:
import numpy as np
import pandas as pd

import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier

In [124]:
diabetes = datasets.load_wine()

df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
y = pd.DataFrame(diabetes.target)

y.columns = ['labels']

In [125]:
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [126]:
y[0:5]

   labels
0       0
1       0
2       0
3       0
4       0

In [127]:
df.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64

In [128]:
print(y.labels.value_counts())

1    71
0    59
2    48
Name: labels, dtype: int64

In [130]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=17)

In [131]:
rf_clf = RandomForestClassifier(n_estimators=200, random_state=0)

y_train_array = np.ravel(y_train)

rf_clf.fit(X_train, y_train_array)

y_pred = rf_clf.predict(X_test)

In [132]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        12

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

In [133]:
y_test_array = np.ravel(y_test)
print(y_test_array)

[1 1 1 0 2 2 0 1 2 0 2 0 1 1 2 2 2 1 1 1 1 1 0 2 1 1 0 1 2 1 2 2 0 0 2 1]

In [134]:
print(y_pred)

[1 1 1 0 2 2 0 1 2 0 2 0 1 1 2 2 2 1 1 1 1 1 0 2 1 1 0 1 2 1 2 2 0 0 2 1]